#!/usr/bin/env bash
# manipulating my ssh client config file to accept private key and authenticate without a password.
host ubuntu
  hostName 172.22.178.95
  User ubuntu
  IdentityFile ~/.ssh/school
  PasswordAuthentication no 
