#!/usr/bin/env bash
#install your load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5652-webs
    bind *:80
    mode http
    balance roundrobin
    server 5946-web-01 3.87.215.189:80 check
    server 5946-web-02 100.26.112.230:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
