#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:
apt-get update -y
apt-get install -y nginx
service nginx start
echo "Holberton School for the win!" | tee /var/www/html/index.html > /dev/null


nginx -s reload
